# Generated by Django 2.1.7 on 2019-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=500)),
                ('published_parsed', models.CharField(max_length=100)),
                ('media_content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
