# Generated by Django 2.1.7 on 2019-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bori', '0002_auto_20190306_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='news_category',
            field=models.CharField(default='default', max_length=2000),
        ),
    ]
