# Generated by Django 2.1.7 on 2019-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bori', '0003_newslist_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcmdNewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=500)),
                ('published_date', models.CharField(max_length=100)),
                ('media_content', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=30)),
                ('news_category', models.CharField(default='default', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsList',
        ),
    ]
