# Generated by Django 2.1.7 on 2019-03-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bori', '0004_auto_20190307_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RcmdNewsList',
            new_name='RcmdNews',
        ),
    ]
