# Generated by Django 2.1.7 on 2019-03-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bori', '0007_auto_20190314_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcmdnews',
            name='created',
        ),
        migrations.RemoveField(
            model_name='rcmdnews',
            name='updated',
        ),
    ]
